### ISSUE TITLE
Custom profile

### ISSUE THREAD

**Issue by SantaLaMuerte** [test502git/awvs13_batch_py3#27]
Hello! How to add scan to custom profile - 12. If i enter name of Scan profile - it not work.. Maybe neet to restart (not test yet) .
What id should i specify to awvs14-scan, or where i can found it (for example my custom scan named -sqli).
Thanks for you api wrapper!

你好！  如何将扫描添加到自定义配置文件 - 12. 如果我输入扫描配置文件的名称 - 它不起作用.. 可能需要重新启动（尚未测试）。
 我应该为 awvs14-scan 指定什么 ID，或者我可以在哪里找到它（例如我的自定义扫描名为 -sqli）。
 感谢您的 api 包装器！

**Comment by SantaLaMuerte** [comment]
curl -X GET https://127.0.0.1:3443/api/v1/scanning_profiles \
  -H 'Accept: application/json' \
  -H 'X-Auth: API_KEY'
  
  i try to use that command with my Api key. but it not work . even if i try localhost and different build for curl command . help plz

**Comment by SantaLaMuerte** [comment]
was try https://localhost:3443/api/v1/users as endpoit but cant configure command propertly

**Comment by hastalamuerte** [comment]
was try https://localhost:3443/api/v1/users as endpoit but cant configure command propertly

**Comment by SantaLaMuerte** [comment]
![image](https://user-images.githubusercontent.com/63853227/234092839-f991e330-7472-4826-94d2-f66812fadd8b.png)
there was easy way)
