### ISSUE TITLE
全部失败

### ISSUE THREAD

**Issue by githack2016** [test502git/awvs13_batch_py3#9]
批量导入了一批致远A8的资产，手工测试很多存在漏洞，联动AWVS全部失败。
![image](https://user-images.githubusercontent.com/19440170/149276667-c3ccc1b3-3305-4817-87ae-2d3bf0200929.png)

**Comment by test502git** [comment]
请先检测awvs是否能正常扫描常规漏洞
确定与脚本有关再提issues
